### ISSUE TITLE
Conditionals of large type cause failure

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#10]
If the C0 compiler must isolate a struct, it generates code that assigns large values to temporary variables. Because this is outside of the Cymbol memory, this causes Coin to fail. 

May or may not cause incorrect results in cc0, no regression tests with this problem currently fail for cc0 - just for coin-exec.

**Comment by robsimmons** [comment]
In cc0, the problematic cases like eagle-funky-access.c0 seem to cause a nonexhaustive match exception in the compiler with -b.

**Comment by frankpfenning** [comment]
Resolved via #27
