### ISSUE TITLE
Namespace conflicts - _tmp, _result, _caller can cause compiler failure

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#11]
Regression tests rjs-basic/evil-\* exhibit this bug.

**Comment by robsimmons** [comment]
Triggered in regression suite:

tests/rjs-basic/evil-name1.c0
tests/rjs-basic/evil-name2.c0
tests/rjs-basic/evil-name3.c0
tests/rjs-basic/evil-name6.c0

**Comment by frankpfenning** [comment]
As of r205, this has been fixed in cc0 by introducing two name spaces:
Symbol.User and Symbol.Internal (see util/symbol.sml).  This signature
was kept backward compatible.

There are currently 4 forms of internal names:

```
_tmp_<n> created by isolation (type/iso.sml)
_result
_caller
<function>__<n> (created by type/dyn-check.sml).
```

When they are printed (in print-c-compact.sml), they are prefixed
with _c0t_ while User symbols are prefixed with _c0_ or _c0v_ (for
local variables) or nothing (for external library functions).

Internal names are never entered into the hash table mapping strings
to their unique names, so it should not be possible to confuse the
Internal and User symbols.

In coin and code, internal symbols should be treated differently from
user symbols.  This could clean up the interactions considerably.

**Comment by robsimmons** [comment]
I've done a quick pass through coin and code; I think I've doe some simplification based on these issues correctly, and also modified dyn-check.sml so that it's correctly making `_result` an internal name. I'll close for now.

**Comment by frankpfenning** [comment]
Actually, it should be calling `Symbol.new "_result"` rather than `Symbol.nsymbol Symbol.Internal "_result"` because the latters enters _result into the symbol table, where it can confuse the parser.

I made that small change and will test it now.

**Comment by robsimmons** [comment]
Reopening - tests/rjs-basic/evil-name3.c0 still causes an error in the VM, which does not distinguish \result from _result.

**Comment by frankpfenning** [comment]
Cannot reproduce this bug.  It works fine in my version (see below).  I also
inspected the byte code, and it is correct except that the comment does not
distinguish between _result, internal and _result, user.  I feel it would be
overkill to make the variable names in the comments unique (and potentially
less readable) as long as the byte code itself is correct, which it appears
to be.

```
% make checkvm
mlton -default-ann "redundantMatch error" -default-ann "sequenceNonUnit error" -verbose 0 -output bin/c0vm-test tests/drivers/c0vm-test.mlb
bin/c0vm-test tests/*/*.c0 tests/*/*.test 

...

Final results:
Successful tests:  2570
Failed tests:      6
Tests with errors: 0
Timeouts: 114

=== Failed test specs: ===
In file /Users/fp/programs/c0/cc0/tests/l4tests1-f11/eagle-funky-access.c0
Test:   return 4 ~ tests/l4tests1-f11/eagle-funky-access.c0
Result: Program failed to compile

In file /Users/fp/programs/c0/cc0/tests/l4tests1-f11/eagle-lots-of-structs.c0
Test:   return 5 ~ tests/l4tests1-f11/eagle-lots-of-structs.c0
Result: Compilation timed out

In file /Users/fp/programs/c0/cc0/tests/l5tests1-f11/eagle-cfold.c0
Test:   return -382401888 ~ tests/l5tests1-f11/eagle-cfold.c0
Result: Compilation timed out

In file /Users/fp/programs/c0/cc0/tests/l5tests1-f11/eagle-funky-access.c0
Test:   return 4 ~ tests/l5tests1-f11/eagle-funky-access.c0
Result: Program failed to compile

In file /Users/fp/programs/c0/cc0/tests/l5tests1-f11/eagle-lots-of-structs.c0
Test:   return 5 ~ tests/l5tests1-f11/eagle-lots-of-structs.c0
Result: Compilation timed out

In file /Users/fp/programs/c0/cc0/tests/l5tests1-f11/lammergeier-piplup.c0
Test:   return 6023 ~ tests/l5tests1-f11/lammergeier-piplup.c0
Result: Compilation timed out
```

**Comment by robsimmons** [comment]
Must not have recompiled cc0, sorry about the false negative.
