### ISSUE TITLE
Bytecode compiler not awesome enough

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#24]
A couple of enhancements to the bytecode compiler would make it more student friendly:
- if(x < y) ... else ... should be compiled directly into an ifcmplt, and the same for the other comparison operations
- generating negative bipushes and integer store variables in non-pathalogical cases would help students naturally write test cases
- longer term, generating negative jumps for branch conditions (perhaps with loops) is a good idea, but that's a later optimization

**Comment by frankpfenning** [comment]
I rewrote the bytecode compiler to directly use comparisons for conditionals and loops (bullet1).

Also, as in bullet2, cc0 -b will now generate negative small constants in the instruction stream,
as argument to bipush.  Not sure what "(negative) integer store variables" means.

I stuck to the design principle that code be layed out in the order in which it occurs
in the source, and I was therefore reluctant to rotate loops.  This means goto's
can have a negative offset, but never conditionals.  A rotated loop:

while (e) s;

goto loop:
body:
  code for s
loop:
  code for e
  if (true) goto body
exit:

would be very easy to do, but invert e and s.  Currently, the compiler produces:

loop:
  code for e
  if (true) goto body
  goto exit:
body:
  code for s
  goto loop
exit:

Thoughts?

Conditionals will always generate forward branches (conditional or unconditional).

**Comment by robsimmons** [comment]
Negative integer store variables meant storing -12512 instead of 12512 in the constant pool when "-12512" appears in the program - the only way to get negative values in the constant pool is to use 0x8####### notation.

What we have here seems sufficiently awesome: we can still do some by-hand tests to test negative conditional jumps and positive gotos, but all were checking for in that case is that students either abstracted correctly or cut-and-pasted consistently.

**Comment by robsimmons** [comment]
(Oh, we already have positive gotos.) Anyway, I like what the compiler currently produces, and the extra signed offsets are a nice touch. I'm happy closing at this point.

**Comment by frankpfenning** [comment]
Just to clarify, I added the "negative integer store variables" in this pass.  If you write x = -129, it will add
the number -129 (0x FF FF FF 7F) to the constant pool.  If you write x = -128, it will bipush -128 (0x80).

**Comment by robsimmons** [comment]
Ok. Sorry for using a wrong and ambiguous word, I was kind of free-associating there.
