### ISSUE TITLE
Purity tracker needs correctly-formatted error messages

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#25]
Right now a syntax error looks like this

```
unionfind.c0:10.4-10.10:error:expected ';', found: 'return'
Compilation failed
```

and the purity checker's errors look like this:

```
error at unionfind.c0:81.15-81.23: assignment may modify previously visible memory.
```

the latter need to look more like the former or tools like code's emacs mode that expect compiler errors to have a particular form are liable to get very confused.

**Comment by frankpfenning** [comment]
Standardized as of revision r219.

Also updated language reference to mention purity checking.
