### ISSUE TITLE
Require conditionals in tertiary expressions to have small type

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#27]
This would allow

```
x ? y.baz.bar : z.foo.bar
```

instead of the following (equivalent by commutative conversion if y and z have the same type)

```
(x ? y.baz : z.foo).bar
```

This change would completely resolve #10

**Comment by robsimmons** [comment]
Rob - investigate whether address-of is still necessary in compilation in this case. 

Answer: no it does not:

```
A[3].f = foo(17);
```

this code first gets the location &(A[3].f), then calculates foo(17), then does the (pure) assignment of the result value into the memory within A[3].f.

**Comment by robsimmons** [comment]
Possible resolutions: 
- Disallow conditionals at large type as described here. 
- Have isolation do commutative conversions to get conditionals of small type.

Both of these would fix stuff of low priority. Who in the compilers class needs to be notified of this?

Assigned to Frank to think about, Rob can implement either solution (especially the first) once Frank thinks about it.

**Comment by robsimmons** [comment]
Decision: pull the trigger on this issue and require condition expressions to have small type.

**Comment by frankpfenning** [comment]
Done, as of revision r216.
