### ISSUE TITLE
Assertion contracts at the end of blocks

### ISSUE THREAD

**Issue by frankpfenning** [frankpfenning/C0#28]
Because we have a hand-written parser, it would now be easy to permit
//@assert contracts at the end of blocks, just before the closing brace.

However, it would complicate the grammar and introduce a potential
ambiguity that could only be resolved with look-ahead.

**Comment by robsimmons** [comment]
I am definitely in favor of this change.

**Comment by frankpfenning** [comment]
Fixed, as of r196.
