### ISSUE TITLE
Move to gc 7.2d

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#31]
I was able to get C0 to compile without any problems on Mountain Lion, except that c0rt failed due to the dependency on GC. The 7.2d version of the Bohem collector works as a drop-in replacement for the previous 7.2alpha version we were using; unless there are objections I'll plan to replace the old GC with the new GC early next week.

**Comment by frankpfenning** [comment]
That seems like a good move.

**Comment by robsimmons** [comment]
Done in r187. The old stuff is in gc-old1, but that should probably just be removed once we get past the beginning of next semester if everything is working.
