### ISSUE TITLE
Remove generation of oper_asn in compiler

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#34]
The compiler generates code for idiv_asn, imod_asn, sal_asn, and sar_asn, but this presumably could be eliminated. Eliminating these functions would simplify the overall architecture, as cc0lib.h could be turned exclusively into a library of macros; we could get rid of cc0lib.c altogether.

**Comment by frankpfenning** [comment]
Done, and added appropriate regression tests in revision r246.

I did not remove these from cc0lib.*, but this would be a logical step for someone who
wanted to clean this up.

**Comment by robsimmons** [comment]
Removed prototypes from cc0lib.h and entirely removed cc0lib.c, which is no longer necessary. (r249)
