### ISSUE TITLE
Remove or fix out-of-date parsers

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#44]
We've discussed removing parse2 in the past; I'm going to go ahead and do that unilaterally.

As for parse1, with the resolution to #28, it's not even clear that there's an easy way to write a YACC parser for C0+contracts (this doesn't affect the compilers course, because assertions are just comments in that setting). But this should eventually either be updated and tested or eliminated, I suppose.

**Comment by frankpfenning** [comment]
Eliminate both of them, if you are at it already.

**Comment by robsimmons** [comment]
Ok - should I wipe out debugger-r10 while I'm at it? It will live on in our hearts and subversion histories.

**Comment by frankpfenning** [comment]
Yes.  I would suggest adding a "history" section to the README file to
catalogue some of these.  I can add some comments, once you write
there what has been eliminated.

There are a few other individual files I want to zap, once you have done
the major work above.

**Comment by robsimmons** [comment]
Cleaned up, added history, also deleted the old QT and recorded that. (I can let go of all tokens now except for the makefile where I'm working on #46.)
