### ISSUE TITLE
C0 mode should disable tabs

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#51]
Without having to do a global kill-all-tabs move, C0 mode should go ahead and assume that C0 code should be always free of tabs.

**Comment by frankpfenning** [comment]
That's easy: if you do a setq-default when you switch to C0
mode then the variable become buffer-local and won't affect
the status of other tabs.

Can you assign this to me?

On Thu, Jan 17, 2013 at 2:53 PM, Robert J. Simmons <notifications@github.com

**Comment by frankpfenning** [comment]
Fixed as of r269 in the repository.
