### ISSUE TITLE
Ternary expressions do not expand typedefs

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#54]
The following code does not typecheck in cc0 as of r268.

``` c0
typedef int* elem;

elem g() {
  return alloc(int);
}

int main() {
  int* i = true ? g() : NULL;
  return 0;
}
```

Thanks to Ben Spinelli in 15-122 Spring 2013 for finding this one.

**Comment by frankpfenning** [comment]
It's not as simple as that: the bug occurs when one of
side of a conditional has indeterminate type (only NULL)
and the other side is a type definition.  Curiously, the
code was correct at some point (still available in a comment)
and then was unfixed.

I'll change it back.
- Frank

On Fri, Mar 29, 2013 at 6:25 PM, Robert J. Simmons <notifications@github.com

**Comment by robsimmons** [comment]
I suspect the change was so that it would give better errors, reporting
'int*' instead of 'elem'?

**Comment by frankpfenning** [comment]
Possibly.  In any case, fixed as of r298.
