### ISSUE TITLE
Implicit declarations of structs cause C compilation to fail

### ISSUE THREAD

**Issue by frankpfenning** [frankpfenning/C0#57]
Enrique Naudon from 15-411, Fall 2013, reported the following bug, where gcc on the output of the C0 compiler fails.  The issue is that that an implicit declaration of a struct in a parameter list has entirely local scope.  If cc0 generated an struct declaration at the beginning of the file (or the companion header file), it would compile correctly without warning or error.

``` c0
//test error

int bar(struct wrapper *foo);

struct wrapper {
  struct s *undef;
};

int main()
{
  struct wrapper *blah = alloc(struct wrapper);

  return bar(blah);
}

struct s {
  int a;
};

int bar(struct wrapper *foo)
{
  foo->undef->a = 10;

  return foo->undef->a;
}
```

**Comment by robsimmons** [comment]
Should be fixed in revision 525, by redundantly re-declaring all structs that appear in parameter lists before the functions, which gives them global scope.
