### ISSUE TITLE
SIGFPE on out-of-range shifts (was: Leftshift and rightshift are slow)

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#6]
Currently, the semantics of shift are that (x << 33), (x << -31), and (x << 1) are all equivalent. This makes code rather slow, however, due to the necessity of C output and the fact that C doesn't define shifts outside the [0, 32) interval.

One alternative is to optimize the compiler - notice constant offsets and fix them appropriately, like we do for division-by-a-constant. 

Another alternative would be to change the semantics so that an arithmetic error is thrown whenever a shift is outside the [0, 32) interval - this causes shift to be a potentially unsafe operation, whereas it's always safe now. Such a change would allow the unsafe runtime to run fast, but it's not totally clear that we care that much about the unsafe runtime.

**Comment by varming** [comment]
On the same note; shifts are currently implemented in a way that makes (x << 33) undefined. This should be a bug.

**Comment by robsimmons** [comment]
Decision: make shift left and shift right outside the [0, 32) range another arithmetic error (raising SIGFPE), and produce constant C shifts when we're shifting by a constant.

**Comment by robsimmons** [comment]
Frank: fix this in cc0, runtime, and language reference, and I'll update regression test appropriately and fix coin/code/c0vm.

**Comment by robsimmons** [comment]
I think I've mostly addressed this issue when I did a once-over on all the runtimes and libraries as of r189.
- Language reference still needs to be updated (Frank)
- Coin/code still need to be updated (Rob)
- Reference c0vm still needs to be updated (Rob)

**Comment by robsimmons** [comment]
Coin updated as of r192.

**Comment by frankpfenning** [comment]
Language reference has been updated.

By the way, the compiler class isn't going to like this change...we move away from
the machine semantics to a more complicated one that requires runtime checking
without improving safety at all.

**Comment by robsimmons** [comment]
Yep, we'd talked about that being the biggest drawback of the change. This
isn't enough tension to make it worth splitting apart the languages, I
presume?
- Rob

**Comment by frankpfenning** [comment]
No, definitely not.  It's minimal additional code.  I blame C, and
some semi-compatibility with C is a stronger motivating force
than a few extra instructions in students' compilers.
- Frank

On Sun, Dec 23, 2012 at 9:31 AM, Robert J. Simmons <notifications@github.com

**Comment by robsimmons** [comment]
r198 updates the reference c0vm, so we're done.
